# Generated by Django 3.2.5 on 2021-08-04 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marka', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=50)),
                ('power', models.IntegerField()),
                ('volume', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
